name: Backup2 BEUP Monitor

on:
  schedule:
    - cron: '4-59/5 * * * *'  # Every 5 minutes, 4 minutes offset
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    timeout-minutes: 8
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run backup2 monitor
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        GITHUB_ACTIONS: 'true'
      run: |
        echo "🆘 Starting Backup2 BEUP Monitor..."
        python discord_monitor.py
        echo "✅ Backup2 monitor completed"