name: Backup3 BEUP Monitor

on:
  schedule:
    - cron: '1-59/5 * * * *'  # Every 5 minutes, 1 minute offset
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    timeout-minutes: 8
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: |
          echo "🔄 Starting Backup3 BEUP Monitor..."
          python discord_monitor.py
          echo "✅ Backup3 monitor completed"
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          GITHUB_ACTIONS: 'true'